require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
